services:



  discovery-server:
    build: ./discoveryserver
    ports:
      - "8888:8888"

  postgres:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=111
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

  gateway-server:
    build: ./gatewayserver
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8888/eureka

volumes:
  postgresql-volume:
    name: postgresql-volume2



