services:



  discovery-server:
    build: ./discoveryserver
    ports:
      - "8888:8888"
    networks:
      - common

  config-server:
    build: ./configserver
    ports:
      - "8079:8079"
    networks:
      - common

  postgres:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=111
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

  gateway-server:
    build: ./gatewayserver
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common

networks:
  common:
    driver: bridge


volumes:
  postgresql-volume:
    name: postgresql-volume2



